#!/usr/bin/env bash
# Generate the shadow-collection environment from the production one.
#
# Generated rather than hand-written for two reasons: the shadow run must carry
# the *complete* current acquisition configuration, and a hand-written copy
# silently rots the moment production gains a setting. Secrets stay out of Git
# because the file is produced on the host from the production file.
#
# Policy is allowlist-first and fail-closed: a key that is neither carried nor
# explicitly dropped aborts the generation, so a newly introduced production
# setting cannot be silently omitted from the shadow run — or silently carried
# into it, if it turns out to be a credential.
set -euo pipefail

source_env="${1:-/etc/job-intel/job-intel.env}"
target_env="${2:-/etc/job-intel/job-intel-shadow.env}"

# Never carried: outbound delivery credentials and destinations.
declare -a DROP=(
  SLACK_BOT_TOKEN
  SLACK_APP_TOKEN
  SLACK_HOME_CHANNEL
  JOB_INTEL_SLACK_WEBHOOK_URL
)

# Overridden rather than copied.
declare -A OVERRIDE=(
  [JOB_INTEL_RUN_TYPE]=shadow
  [JOB_INTEL_DELIVERY_DISABLED]=1
  [JOB_INTEL_ENV_FILE]="$target_env"
  [SEMANTIC_SHADOW_ADVISORY_ENABLED]=0
)

# Carried verbatim. Prefixes keep acquisition configuration complete without
# enumerating every ATS seed by hand.
declare -a CARRY_PREFIX=(
  JOB_INTEL_
  HERMES_HOME
  HERMES_SKIP_CHMOD
  PLAYWRIGHT_BROWSERS_PATH
  XDG_CACHE_HOME
  SCORING_MODEL_VERSION
)

is_dropped() {
  local key="$1"
  for name in "${DROP[@]}"; do [[ "$key" == "$name" ]] && return 0; done
  return 1
}

is_carried() {
  local key="$1"
  for prefix in "${CARRY_PREFIX[@]}"; do [[ "$key" == "$prefix"* ]] && return 0; done
  return 1
}

[[ -r "$source_env" ]] || { echo "cannot read $source_env" >&2; exit 2; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/job_intel_make_shadow_env.sh from $source_env"
  echo "# Delivery credentials are absent by policy; the kill-switch is the primary control."
} >"$tmp"

unknown=()
while IFS= read -r line; do
  [[ -z "$line" || "$line" == \#* || "$line" != *=* ]] && continue
  key="${line%%=*}"
  key="${key// /}"
  if is_dropped "$key"; then continue; fi
  if [[ -n "${OVERRIDE[$key]+set}" ]]; then continue; fi
  if is_carried "$key"; then printf '%s\n' "$line" >>"$tmp"; continue; fi
  unknown+=("$key")
done <"$source_env"

if ((${#unknown[@]})); then
  echo "unclassified keys in $source_env: ${unknown[*]}" >&2
  echo "add each to DROP or to CARRY_PREFIX and re-run; refusing to guess" >&2
  exit 3
fi

for key in "${!OVERRIDE[@]}"; do printf '%s=%s\n' "$key" "${OVERRIDE[$key]}" >>"$tmp"; done

install -o root -g hermes -m 0640 "$tmp" "$target_env"
echo "wrote $target_env"
