#!/usr/bin/env bash
# Generate the shadow-collection environment from the production one.
#
# Generated rather than hand-written for two reasons: the shadow run must carry
# the *complete* current acquisition configuration, and a hand-written copy
# silently rots the moment production gains a setting. Secrets stay out of Git
# because the file is produced on the host from the production file.
#
# Classification is fail-closed in both directions:
#   - a key matching a credential-shaped pattern is refused unless it appears in
#     exactly one of DROP or CARRY_SECRET, so a future JOB_INTEL_*_TOKEN cannot
#     ride in on a prefix rule;
#   - a key matching nothing at all aborts generation, so a new production
#     setting cannot be silently omitted.
set -euo pipefail

source_env="${1:-/etc/job-intel/job-intel.env}"
target_env="${2:-/etc/job-intel/job-intel-shadow.env}"

# Never carried: outbound delivery credentials and destinations.
declare -a DROP=(
  SLACK_BOT_TOKEN
  SLACK_APP_TOKEN
  SLACK_HOME_CHANNEL
  JOB_INTEL_SLACK_WEBHOOK_URL
)

# Credential-shaped, but required by acquisition and therefore carried on
# purpose. Every entry is a deliberate decision, not a prefix side effect.
declare -a CARRY_SECRET=(
  JOB_INTEL_HH_CLIENT_ID
  JOB_INTEL_HH_CLIENT_SECRET
  JOB_INTEL_HH_TOKEN_CACHE
)

# Overridden rather than copied.
declare -A OVERRIDE=(
  [JOB_INTEL_RUN_TYPE]=shadow
  [JOB_INTEL_DELIVERY_DISABLED]=1
  [JOB_INTEL_ENV_FILE]="$target_env"
  [SEMANTIC_SHADOW_ADVISORY_ENABLED]=0
)

# Carried verbatim when they are not credential-shaped.
declare -a CARRY_PREFIX=(
  JOB_INTEL_
  HERMES_HOME
  HERMES_SKIP_CHMOD
  PLAYWRIGHT_BROWSERS_PATH
  XDG_CACHE_HOME
  SCORING_MODEL_VERSION
)

# A key whose name looks like a credential or a delivery destination.
CREDENTIAL_PATTERN='(TOKEN|SECRET|PASSWORD|WEBHOOK|API_KEY|CREDENTIAL|SLACK|TELEGRAM|WHATSAPP|CHANNEL|CHAT_ID)'

in_list() {
  local key="$1"; shift
  for name in "$@"; do [[ "$key" == "$name" ]] && return 0; done
  return 1
}

has_prefix() {
  local key="$1"
  for prefix in "${CARRY_PREFIX[@]}"; do [[ "$key" == "$prefix"* ]] && return 0; done
  return 1
}

[[ -r "$source_env" ]] || { echo "cannot read $source_env" >&2; exit 2; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/job_intel_make_shadow_env.sh from $source_env"
  echo "# Delivery credentials are absent by policy; the kill-switch is the primary control."
} >"$tmp"

unknown=()
unclassified_secret=()
while IFS= read -r line; do
  [[ -z "$line" || "$line" == \#* || "$line" != *=* ]] && continue
  key="${line%%=*}"
  key="${key// /}"

  if in_list "$key" "${DROP[@]}"; then continue; fi
  if [[ -n "${OVERRIDE[$key]+set}" ]]; then continue; fi

  # Credential-shaped keys never ride in on a prefix rule.
  if [[ "$key" =~ $CREDENTIAL_PATTERN ]]; then
    if in_list "$key" "${CARRY_SECRET[@]}"; then
      printf '%s\n' "$line" >>"$tmp"
      continue
    fi
    unclassified_secret+=("$key")
    continue
  fi

  if has_prefix "$key"; then printf '%s\n' "$line" >>"$tmp"; continue; fi
  unknown+=("$key")
done <"$source_env"

if ((${#unclassified_secret[@]})); then
  echo "credential-shaped keys not classified in $source_env: ${unclassified_secret[*]}" >&2
  echo "add each to DROP (never carried) or to CARRY_SECRET (carried on purpose); refusing to guess" >&2
  exit 4
fi

if ((${#unknown[@]})); then
  echo "unclassified keys in $source_env: ${unknown[*]}" >&2
  echo "add each to DROP or to CARRY_PREFIX and re-run; refusing to guess" >&2
  exit 3
fi

for key in "${!OVERRIDE[@]}"; do printf '%s=%s\n' "$key" "${OVERRIDE[$key]}" >>"$tmp"; done

if [[ "${SHADOW_ENV_STDOUT:-0}" == "1" ]]; then
  cat "$tmp"
else
  install -o root -g hermes -m 0640 "$tmp" "$target_env"
  echo "wrote $target_env"
fi
